include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enforce trailing commas
    require_trailing_commas: true
    
    # Enforce const keyword
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true